# 1. Convolution
_Author: Maurice Snoeren_

In this notebook we will investigate the convolution part of convolutional neural networks (CNNs). This is a special type of artificial neural network that is used within computer vision. In 2012 there was a breakthrough in the vision area. AlexNet competed in the ImageNet Large Scale Visual Recognition Challenge in 2012. This was a deep convolutional neural network, designed by Alex Krizhevsky. The network achieved a top-5 error of 15,3%. Object detection has been become feasable with this technology.

Convolutional neural networks (CNNs) do something very mush different than normal artificial neural networks (ANNs). CNNs extract specific features from an image using the mathematical convolution. This convolution can be seen a filtering the image to extract lines, circles, etc. It contains a lot of layers and each convolution layer is able to extract more complex features. Where the first convolution layer matchers horizontal and vertical lines, the fifth convolution layer is able to extract full face features or trees for example. This made CNNs outperform existing methods. Normal ANNs are not able to detect a lot of different objects and large images are not easy to be used as well.

In [1]:
#!pip install opencv-python

import cv2 
import numpy as np

def process_image(image):
    image = cv2.imread(image) 
    image = cv2.cvtColor(src=image, code=cv2.COLOR_BGR2GRAY) 
    return image

def convolve2D(image, kernel, padding=0, strides=1):
    # Cross Correlation
    kernel = np.flipud(np.fliplr(kernel))

    # Gather Shapes of Kernel + Image + Padding
    xKernShape = kernel.shape[0]
    yKernShape = kernel.shape[1]
    xImgShape = image.shape[0]
    yImgShape = image.shape[1]

    # Shape of Output Convolution
    xOutput = int(((xImgShape - xKernShape + 2 * padding) / strides) + 1)
    yOutput = int(((yImgShape - yKernShape + 2 * padding) / strides) + 1)
    output = np.zeros((xOutput, yOutput))

    # Apply Equal Padding to All Sides
    if padding != 0:
        imagePadded = np.zeros((image.shape[0] + padding*2, image.shape[1] + padding*2))
        imagePadded[int(padding):int(-1 * padding), int(padding):int(-1 * padding)] = image
        print(imagePadded)
    else:
        imagePadded = image

    # Iterate through image
    for y in range(image.shape[1]):
        # Exit Convolution
        if y > image.shape[1] - yKernShape:
            break
        # Only Convolve if y has gone down by the specified Strides
        if y % strides == 0:
            for x in range(image.shape[0]):
                # Go to next row once kernel is out of bounds
                if x > image.shape[0] - xKernShape:
                    break
                try:
                    # Only Convolve if x has moved by the specified Strides
                    if x % strides == 0:
                        output[x, y] = (kernel * imagePadded[x: x + xKernShape, y: y + yKernShape]).sum()
                except:
                    break

    return output

In [16]:
# Grayscale Image
image = process_image('images/skyline.jpg')
#image = process_image('images/test.jpg')

In [17]:
# Edge Detection Kernel
kernel = np.array(
    [[-1, -1, -1],
     [-1, 8, -1],
     [-1, -1, -1]
])

output = convolve2D(image, kernel, padding=2)
cv2.imwrite('images/image_edges.jpg', output)

[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0. 78. ... 44.  0.  0.]
 ...
 [ 0.  0. 40. ... 17.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]


True

In [18]:
# Edge Detection Kernel
kernel = np.array(
    [[-1, 0, 1],
     [-1, 0, 1],
     [-1, 0, 1]
])

output = convolve2D(image, kernel, padding=2)
cv2.imwrite('images/image_right_edges.jpg', output)

[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0. 78. ... 44.  0.  0.]
 ...
 [ 0.  0. 40. ... 17.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]


True

In [11]:
# Edge Detection Kernel
kernel = np.array(
    [[1, 0, -1],
     [1, 0, -1],
     [1, 0, -1]
])

output = convolve2D(image, kernel, padding=2)
cv2.imwrite('images/image_left_edges.jpg', output)

[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0. 255. ... 255.   0.   0.]
 ...
 [  0.   0. 255. ... 255.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]


True

In [12]:
# Edge Detection Kernel
kernel = np.array(
    [[1, 1, 1],
     [0, 0, 0],
     [-1, -1, -1]
])

output = convolve2D(image, kernel, padding=2)
cv2.imwrite('images/image_upper_edges.jpg', output)

[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0. 255. ... 255.   0.   0.]
 ...
 [  0.   0. 255. ... 255.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]


True

In [19]:
# Edge Detection Kernel
kernel = np.array(
    [[0, 0, 0, 0, 0],
     [0, 1/9, 1/9, 1/9, 0],
     [0, 1/9, 1/9, 1/9, 0],
     [0, 1/9, 1/9, 1/9, 0],
     [0, 0, 0, 0, 0],
])

output = convolve2D(image, kernel, padding=2)
cv2.imwrite('images/image_blur.jpg', output)

[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0. 78. ... 44.  0.  0.]
 ...
 [ 0.  0. 40. ... 17.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]


True

## Sources

- https://cs231n.github.io/convolutional-networks/
- https://www.researchgate.net/profile/Paresh-Kamble/publication/333643310_Convolutional_Neural_Networks_-A_breakthrough_in_Computer_Vision/links/5cf901b9299bf1fb185bcee2/Convolutional-Neural-Networks-A-breakthrough-in-Computer-Vision.pdf
